export const _mockModelData = {
    itemCode: "VH-2023-001",
    itemSuffix: "001",
    brandName: "Toyota",
    isActive: true,
    itemDescription: "Toyota Hilux 2.7L Doble Cabina 4x4 Gasolina Manual",
    relationshipDescription: "Vehículo Propio",
    countryName: "Japón",
    className: "Camioneta",
    subclassName: "Doble Cabina",
    antTypeDescription: "Particular",
    antSubtypeDescription: "Camioneta",
    displacement: 2694,
    capacity: 5,
    tonnage: 1.5,
    transmissionDescription: "Manual",
    requiresCustomerProfile: true,
    ivaDescription: "12%",
    ecoValueDescription: "0%",
    qrCommercialCode: "https://example.com/qr-code",
    depreciationPercentages: [
        { year: 1, depreciationPercentage: 20 },
        { year: 2, depreciationPercentage: 15 },
        { year: 3, depreciationPercentage: 10 },
    ],
    images: [
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1000",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&q=80&w=1000",
    ],
    interestDetails: [
        { id: 1, modelYear: 2023, quotaFrom: 10000, quotaTo: 20000, interestRate: 5.5 },
        { id: 2, modelYear: 2023, quotaFrom: 20001, quotaTo: 30000, interestRate: 4.5 },
    ],
};
