import {
	isArray,
	isEmpty,
	isNumber,
	isObject,
	isString,
	isUndefined,
	isValidEmailFormat,
	isValidMaskFormat,
} from './booleansChecks';
import { getInstance, securityApi } from './configAxios';
import { getFormatCurrency } from './currencies';
import { getCurrentDate } from './dates';
import {
	getDropdownFormattedOptions,
	getFormattedAddress,
	getFormattedFieldValue,
	getFormattedSchemaValues,
	getLabelFromValue,
	getSchemaColumns,
	getSchemaFields,
	getNumberFromStorage,
	getStringFromStorage,
	parseValidDateITSA,
} from './formats';
import {
	cleanObject,
	createValueLabelMap,
	filterMenuSidebar,
	filterMenuTree,
	findLastChild,
	generateFilteredMenu,
	getAllMenuKeys,
	getMappedOptionFromAPI,
	getMappedOptionFromLocal,
	getNestedValue,
	hasAllRequiredFields,
	mapPermissionsToMenuFormat,
} from './objects';
import { transformModuleToMenuData } from './menu/menuDataTransformer';
import { clearLocalStorage } from './session';
import { codeUserInputValidation } from './codeUserInputValidation';
import {
	isLikelyGibberishWord,
	isValidArgument,
	normalizeArgumentText,
	validateArgument,
	validateArgumentUnified,
	validateArgumentWithIA,
} from './validateArgument';
import {
	capitalize,
	isRouteActive,
	toTitleCase,
	getMicroFrontendByPath,
	joinUrl,
	isNumericOnly,
	filterNumericOnly,
	filterPositiveNumbersOnly,
	splitDelimitedValues,
} from './strings';
import {
	addOrderParamIfMissing,
	buildQueryParams,
	cleanPath,
	clearURLParams,
	fillRoute,
	getParamsFromURL,
	getQueryParam,
	updateURLParams,
} from './urls';

import {
	normalizeStatus,
	uppercaseStrings,
	findProgramIdByPath,
	findProgramIdByPathFromAgencies,
	generateUuid,
	findContainedPaths,
	getOriginFromUrl,
	formatMoneyIfValid,
	roundUpDecimal,
} from './functions';
import {
	handleAddChildTreeNode,
	updateItemTreeNodeById,
	addChildByParentId,
	addChildrenByParentId,
	updateChildUnderParent,
} from './treeNode';

export {
	addOrderParamIfMissing,
	buildQueryParams,
	capitalize,
	cleanObject,
	cleanPath,
	clearLocalStorage,
	clearURLParams,
	codeUserInputValidation,
	createValueLabelMap,
	fillRoute,
	filterMenuSidebar,
	filterMenuTree,
	filterNumericOnly,
	filterPositiveNumbersOnly,
	splitDelimitedValues,
	findLastChild,
	findProgramIdByPath,
	findProgramIdByPathFromAgencies,
	findContainedPaths,
	formatMoneyIfValid,
	getOriginFromUrl,
	generateUuid,
	getNumberFromStorage,
	getStringFromStorage,
	getInstance,
	parseValidDateITSA,
	generateFilteredMenu,
	getAllMenuKeys,
	getCurrentDate,
	getDropdownFormattedOptions,
	getFormatCurrency,
	getFormattedAddress,
	getFormattedFieldValue,
	getFormattedSchemaValues,
	getLabelFromValue,
	getMappedOptionFromAPI,
	getMappedOptionFromLocal,
	getNestedValue,
	getParamsFromURL,
	getQueryParam,
	getSchemaColumns,
	getSchemaFields,
	getMicroFrontendByPath,
	hasAllRequiredFields,
	handleAddChildTreeNode,
	isArray,
	isEmpty,
	isNumber,
	isNumericOnly,
	isObject,
	isRouteActive,
	isString,
	isUndefined,
	isValidEmailFormat,
	isValidMaskFormat,
	joinUrl,
	mapPermissionsToMenuFormat,
	normalizeStatus,
	roundUpDecimal,
	securityApi,
	toTitleCase,
	transformModuleToMenuData,
	uppercaseStrings,
	updateURLParams,
	updateItemTreeNodeById,
	addChildByParentId,
	addChildrenByParentId,
	updateChildUnderParent,
	isValidArgument,
	isLikelyGibberishWord,
	normalizeArgumentText,
	validateArgument,
	validateArgumentUnified,
	validateArgumentWithIA,
};
